version: '3.8'

services:
  drone-scanner:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
      - ./config:/root/config
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/root/data/scanner.db
      - BACKEND_URL=http://localhost:8080
    restart: unless-stopped
    networks:
      - scanner-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - drone-scanner
    restart: unless-stopped
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge

volumes:
  scanner-data:
  scanner-logs:
